spring.application.name=linkshortener

spring.datasource.url=jdbc:postgresql://db:5432/linkshortener
spring.datasource.username=postgres
spring.datasource.password=maneger
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
